"""Frozen, human-authored carriers for three independent token settlements."""

CAMPAIGNS = {
    "only-focus": {
        "slug": "only-focus-the-weld-spans-the-whole-focused-constituent-2",
        "target_hash": "0508f019dae135d82437c2a794276f0d3b5da53d1f4068440e61297d7b570cec",
        "construct": "only-<focus>",
        "models": ["cl100k_base", "o200k_base"],
        "comparison_identity": {
            "comparator_genre": "bare-only-placement-v1",
            "pair_rendering": "inline-single-sentence",
            "tokenizer_roster": ["cl100k_base", "o200k_base"],
        },
        "strata": {"subject": 8, "verb": 8, "object-nominal": 8, "adjunct": 8},
        "items": [
            {"id": "s01", "stratum": "subject", "english": "only Aster compiled the manifest.", "ainglish": "only-Aster compiled the manifest."},
            {"id": "s02", "stratum": "subject", "english": "only Boreal signed the ledger.", "ainglish": "only-Boreal signed the ledger."},
            {"id": "s03", "stratum": "subject", "english": "only the backup custodian accessed the vault.", "ainglish": "only-the-backup-custodian accessed the vault."},
            {"id": "s04", "stratum": "subject", "english": "only three auditors inspected the seal.", "ainglish": "only-three-auditors inspected the seal."},
            {"id": "s05", "stratum": "subject", "english": "only our release manager approved the mirror.", "ainglish": "only-our-release-manager approved the mirror."},
            {"id": "s06", "stratum": "subject", "english": "only the database owner rotated the key.", "ainglish": "only-the-database-owner rotated the key."},
            {"id": "s07", "stratum": "subject", "english": "only agent Seven challenged the result.", "ainglish": "only-agent-Seven challenged the result."},
            {"id": "s08", "stratum": "subject", "english": "only the primary mirror retained the object.", "ainglish": "only-the-primary-mirror retained the object."},
            {"id": "v01", "stratum": "verb", "english": "Nora only inspected the headers.", "ainglish": "Nora only-inspected the headers."},
            {"id": "v02", "stratum": "verb", "english": "the daemon only validated the checksum.", "ainglish": "the daemon only-validated the checksum."},
            {"id": "v03", "stratum": "verb", "english": "we only copied the metadata.", "ainglish": "we only-copied the metadata."},
            {"id": "v04", "stratum": "verb", "english": "they only reordered the queue.", "ainglish": "they only-reordered the queue."},
            {"id": "v05", "stratum": "verb", "english": "the reviewer only annotated the failure.", "ainglish": "the reviewer only-annotated the failure."},
            {"id": "v06", "stratum": "verb", "english": "I only compressed the bundle.", "ainglish": "I only-compressed the bundle."},
            {"id": "v07", "stratum": "verb", "english": "Kepler only opened the attachment.", "ainglish": "Kepler only-opened the attachment."},
            {"id": "v08", "stratum": "verb", "english": "the worker only counted the records.", "ainglish": "the worker only-counted the records."},
            {"id": "o01", "stratum": "object-nominal", "english": "the runner modified only the timeout.", "ainglish": "the runner modified only-the-timeout."},
            {"id": "o02", "stratum": "object-nominal", "english": "we mirrored only two public bundles.", "ainglish": "we mirrored only-two-public-bundles."},
            {"id": "o03", "stratum": "object-nominal", "english": "the filter retained only urgent alerts.", "ainglish": "the filter retained only-urgent-alerts."},
            {"id": "o04", "stratum": "object-nominal", "english": "Mira disclosed only her final estimate.", "ainglish": "Mira disclosed only-her-final-estimate."},
            {"id": "o05", "stratum": "object-nominal", "english": "the scanner indexed only the signed archive.", "ainglish": "the scanner indexed only-the-signed-archive."},
            {"id": "o06", "stratum": "object-nominal", "english": "I restored only one damaged shard.", "ainglish": "I restored only-one-damaged-shard."},
            {"id": "o07", "stratum": "object-nominal", "english": "the policy permits only read operations.", "ainglish": "the policy permits only-read-operations."},
            {"id": "o08", "stratum": "object-nominal", "english": "we published only the compact report.", "ainglish": "we published only-the-compact-report."},
            {"id": "a01", "stratum": "adjunct", "english": "the scheduler wakes only on weekdays.", "ainglish": "the scheduler wakes only-on-weekdays."},
            {"id": "a02", "stratum": "adjunct", "english": "the alert fires only after two failures.", "ainglish": "the alert fires only-after-two-failures."},
            {"id": "a03", "stratum": "adjunct", "english": "the service listens only inside the private network.", "ainglish": "the service listens only-inside-the-private-network."},
            {"id": "a04", "stratum": "adjunct", "english": "the refund runs only with manager consent.", "ainglish": "the refund runs only-with-manager-consent."},
            {"id": "a05", "stratum": "adjunct", "english": "the archive unlocks only during the audit window.", "ainglish": "the archive unlocks only-during-the-audit-window."},
            {"id": "a06", "stratum": "adjunct", "english": "the webhook retries only for transient errors.", "ainglish": "the webhook retries only-for-transient-errors."},
            {"id": "a07", "stratum": "adjunct", "english": "the robot moves only along marked lanes.", "ainglish": "the robot moves only-along-marked-lanes."},
            {"id": "a08", "stratum": "adjunct", "english": "the rule applies only before finalization.", "ainglish": "the rule applies only-before-finalization."},
        ],
    },
    "verifier-at": {
        "slug": "verifier-at-vantage-tier-route-verification-effort-and-price",
        "target_hash": "9b7692e1e03da59878b221f3346513d50a97fef8dd6a010745dd7518d56b05e9",
        "construct": "verifier-at(<vantage>;<tier>)",
        "models": ["cl100k_base", "o200k_base"],
        "comparison_identity": {
            "comparator_genre": "lossless-mapping-in-context-v1",
            "pair_rendering": "inline-single-sentence",
            "tokenizer_roster": ["cl100k_base", "o200k_base"],
        },
        "strata": {"re-derivable": 6, "witnessed": 5, "testimony": 5},
        "items": [
            {"id": "r01", "stratum": "re-derivable", "english": "The image has digest d91f, and its correctness is checkable from the public registry by recomputing from public inputs and trusting nobody.", "ainglish": "The image has digest d91f verifier-at(public-registry;re-derivable)."},
            {"id": "r02", "stratum": "re-derivable", "english": "The dependency lock resolves to version 8.4, and its correctness is checkable from the public lockfile by recomputing from public inputs and trusting nobody.", "ainglish": "The dependency lock resolves to version 8.4 verifier-at(public-lockfile;re-derivable)."},
            {"id": "r03", "stratum": "re-derivable", "english": "The dataset contains 4096 rows, and its correctness is checkable from the published shard by recomputing from public inputs and trusting nobody.", "ainglish": "The dataset contains 4096 rows verifier-at(published-shard;re-derivable)."},
            {"id": "r04", "stratum": "re-derivable", "english": "The package archive matches checksum 7c2a, and its correctness is checkable from the release assets by recomputing from public inputs and trusting nobody.", "ainglish": "The package archive matches checksum 7c2a verifier-at(release-assets;re-derivable)."},
            {"id": "r05", "stratum": "re-derivable", "english": "The certificate expires on 14 October, and its correctness is checkable from the public certificate by recomputing from public inputs and trusting nobody.", "ainglish": "The certificate expires on 14 October verifier-at(public-certificate;re-derivable)."},
            {"id": "r06", "stratum": "re-derivable", "english": "The source archive contains commit 2f8b, and its correctness is checkable from the public repository by recomputing from public inputs and trusting nobody.", "ainglish": "The source archive contains commit 2f8b verifier-at(public-repository;re-derivable)."},
            {"id": "w01", "stratum": "witnessed", "english": "The secure door opened at 07:12, and its correctness is checkable from the access-controller event left by an independent party with a stake.", "ainglish": "The secure door opened at 07:12 verifier-at(access-controller-event;witnessed)."},
            {"id": "w02", "stratum": "witnessed", "english": "The transfer settled yesterday, and its correctness is checkable from the receiving bank's receipt left by an independent party with a stake.", "ainglish": "The transfer settled yesterday verifier-at(receiving-bank-receipt;witnessed)."},
            {"id": "w03", "stratum": "witnessed", "english": "The sample arrived frozen, and its correctness is checkable from the laboratory intake record left by an independent party with a stake.", "ainglish": "The sample arrived frozen verifier-at(laboratory-intake;witnessed)."},
            {"id": "w04", "stratum": "witnessed", "english": "The device was calibrated in June, and its correctness is checkable from the service certificate left by an independent party with a stake.", "ainglish": "The device was calibrated in June verifier-at(service-certificate;witnessed)."},
            {"id": "w05", "stratum": "witnessed", "english": "The pager was acknowledged at 03:15, and its correctness is checkable from the paging provider's event left by an independent party with a stake.", "ainglish": "The pager was acknowledged at 03:15 verifier-at(paging-provider-event;witnessed)."},
            {"id": "t01", "stratum": "testimony", "english": "The interface seemed clearer, and its correctness rests on the claimant's own word with no independent trace.", "ainglish": "The interface seemed clearer verifier-at(self;testimony)."},
            {"id": "t02", "stratum": "testimony", "english": "The draft felt complete, and its correctness rests on the claimant's own word with no independent trace.", "ainglish": "The draft felt complete verifier-at(self;testimony)."},
            {"id": "t03", "stratum": "testimony", "english": "The negotiation sounded constructive, and its correctness rests on the claimant's own word with no independent trace.", "ainglish": "The negotiation sounded constructive verifier-at(self;testimony)."},
            {"id": "t04", "stratum": "testimony", "english": "The experiment looked promising, and its correctness rests on the claimant's own word with no independent trace.", "ainglish": "The experiment looked promising verifier-at(self;testimony)."},
            {"id": "t05", "stratum": "testimony", "english": "The plan appears practical, and its correctness rests on the claimant's own word with no independent trace.", "ainglish": "The plan appears practical verifier-at(self;testimony)."},
        ],
    },
    "grader-eq-graded": {
        "slug": "grader-eq-graded",
        "target_hash": "013f8325e89778e98519f0e19bb1d64cd073e4e1fed0efcc6652545630475d7c",
        "construct": "grader=graded",
        "models": ["cl100k_base", "o200k_base"],
        "comparison_identity": {
            "comparator_genre": "lossless-mapping-in-context-v1",
            "pair_rendering": "inline-single-sentence",
            "tokenizer_roster": ["cl100k_base", "o200k_base"],
        },
        "strata": {"self-reference": 16},
        "items": [
            {"id": "g01", "stratum": "self-reference", "english": "The parser validator imports the parser's own grammar, so its pass certifies agreement-with-self rather than correctness.", "ainglish": "The parser validator is grader=graded."},
            {"id": "g02", "stratum": "self-reference", "english": "The fraud review is performed by the analyst whose labels are being reviewed, so its pass certifies agreement-with-self rather than correctness.", "ainglish": "The fraud review is grader=graded."},
            {"id": "g03", "stratum": "self-reference", "english": "The agent assigns the score to its own answer, so the score certifies agreement-with-self rather than correctness.", "ainglish": "The answer score is grader=graded."},
            {"id": "g04", "stratum": "self-reference", "english": "The recommender is evaluated using relevance labels produced by the same recommender, so the result certifies agreement-with-self rather than correctness.", "ainglish": "The recommender evaluation is grader=graded."},
            {"id": "g05", "stratum": "self-reference", "english": "The forecaster also writes the outcome labels used to score the forecast, so the score certifies agreement-with-self rather than correctness.", "ainglish": "The forecast score is grader=graded."},
            {"id": "g06", "stratum": "self-reference", "english": "The OCR check compares the transcription with a second transcription from the same engine, so agreement certifies agreement-with-self rather than correctness.", "ainglish": "The OCR check is grader=graded."},
            {"id": "g07", "stratum": "self-reference", "english": "The serializer test derives its expected bytes by calling the serializer under test, so the pass certifies agreement-with-self rather than correctness.", "ainglish": "The serializer test is grader=graded."},
            {"id": "g08", "stratum": "self-reference", "english": "The policy audit reads both the policy and its expected findings from one generated file, so the pass certifies agreement-with-self rather than correctness.", "ainglish": "The policy audit is grader=graded."},
            {"id": "g09", "stratum": "self-reference", "english": "The route checker builds its expected URLs from the router it checks, so the pass certifies agreement-with-self rather than correctness.", "ainglish": "The route checker is grader=graded."},
            {"id": "g10", "stratum": "self-reference", "english": "The classifier judges its predictions using labels it generated itself, so the score certifies agreement-with-self rather than correctness.", "ainglish": "The classifier score is grader=graded."},
            {"id": "g11", "stratum": "self-reference", "english": "The inventory audit compares the warehouse list with a copy from the same warehouse system, so the match certifies agreement-with-self rather than correctness.", "ainglish": "The inventory audit is grader=graded."},
            {"id": "g12", "stratum": "self-reference", "english": "The spreadsheet verifies its totals using the same broken formula copied into a check column, so the match certifies agreement-with-self rather than correctness.", "ainglish": "The spreadsheet check is grader=graded."},
            {"id": "g13", "stratum": "self-reference", "english": "The benchmark answer key was generated by the system taking the benchmark, so the pass certifies agreement-with-self rather than correctness.", "ainglish": "The benchmark is grader=graded."},
            {"id": "g14", "stratum": "self-reference", "english": "The database migration verifies rows with a query copied from the migration itself, so the pass certifies agreement-with-self rather than correctness.", "ainglish": "The migration verification is grader=graded."},
            {"id": "g15", "stratum": "self-reference", "english": "The sensor calibrates itself against its own current reading, so the green status certifies agreement-with-self rather than correctness.", "ainglish": "The sensor calibration is grader=graded."},
            {"id": "g16", "stratum": "self-reference", "english": "The summary is rated for fidelity by the model that wrote it, so the rating certifies agreement-with-self rather than correctness.", "ainglish": "The summary rating is grader=graded."},
        ],
    },
}
