"""Frozen, human-authored carriers for three independent token settlements."""

CAMPAIGNS = {
    "only-focus-successor": {
        "slug": "only-focus-the-weld-spans-the-whole-focused-constituent-2",
        "target_hash": "0508f019dae135d82437c2a794276f0d3b5da53d1f4068440e61297d7b570cec",
        "construct": "only-<focus>",
        "tokenizer_version": "0.13.0",
        "models": ["cl100k_base", "o200k_base"],
        "comparison_identity": {
            "comparator_genre": "bare-only-placement-v1",
            "pair_rendering": "inline-single-sentence",
            "tokenizer_roster": ["cl100k_base", "o200k_base"],
        },
        "strata": {"subject": 8, "verb": 8, "object-nominal": 8, "adjunct": 8},
        "items": [
            {"id": "s01b", "stratum": "subject", "english": "only Meridian acknowledged the waiver.", "ainglish": "only-Meridian acknowledged the waiver."},
            {"id": "s02b", "stratum": "subject", "english": "only Solace reopened the incident.", "ainglish": "only-Solace reopened the incident."},
            {"id": "s03b", "stratum": "subject", "english": "only the overnight coordinator viewed the transcript.", "ainglish": "only-the-overnight-coordinator viewed the transcript."},
            {"id": "s04b", "stratum": "subject", "english": "only four maintainers received the notice.", "ainglish": "only-four-maintainers received the notice."},
            {"id": "s05b", "stratum": "subject", "english": "only her delegated reviewer accepted the handoff.", "ainglish": "only-her-delegated-reviewer accepted the handoff."},
            {"id": "s06b", "stratum": "subject", "english": "only the regional service owner cancelled the drill.", "ainglish": "only-the-regional-service-owner cancelled the drill."},
            {"id": "s07b", "stratum": "subject", "english": "only operator Twelve questioned the timestamp.", "ainglish": "only-operator-Twelve questioned the timestamp."},
            {"id": "s08b", "stratum": "subject", "english": "only the secondary replica preserved the annotation.", "ainglish": "only-the-secondary-replica preserved the annotation."},
            {"id": "v01b", "stratum": "verb", "english": "Lumen only compared the signatures.", "ainglish": "Lumen only-compared the signatures."},
            {"id": "v02b", "stratum": "verb", "english": "the relay only forwarded the envelope.", "ainglish": "the relay only-forwarded the envelope."},
            {"id": "v03b", "stratum": "verb", "english": "we only renamed the checkpoint.", "ainglish": "we only-renamed the checkpoint."},
            {"id": "v04b", "stratum": "verb", "english": "they only postponed the rehearsal.", "ainglish": "they only-postponed the rehearsal."},
            {"id": "v05b", "stratum": "verb", "english": "the archivist only catalogued the addendum.", "ainglish": "the archivist only-catalogued the addendum."},
            {"id": "v06b", "stratum": "verb", "english": "I only translated the summary.", "ainglish": "I only-translated the summary."},
            {"id": "v07b", "stratum": "verb", "english": "Vesper only photographed the label.", "ainglish": "Vesper only-photographed the label."},
            {"id": "v08b", "stratum": "verb", "english": "the monitor only recorded the heartbeat.", "ainglish": "the monitor only-recorded the heartbeat."},
            {"id": "o01b", "stratum": "object-nominal", "english": "the verifier cached only the newest attestation.", "ainglish": "the verifier cached only-the-newest-attestation."},
            {"id": "o02b", "stratum": "object-nominal", "english": "we exported only five anonymized samples.", "ainglish": "we exported only-five-anonymized-samples."},
            {"id": "o03b", "stratum": "object-nominal", "english": "the router accepted only encrypted packets.", "ainglish": "the router accepted only-encrypted-packets."},
            {"id": "o04b", "stratum": "object-nominal", "english": "Juniper disclosed only their provisional finding.", "ainglish": "Juniper disclosed only-their-provisional-finding."},
            {"id": "o05b", "stratum": "object-nominal", "english": "the librarian scanned only the damaged appendix.", "ainglish": "the librarian scanned only-the-damaged-appendix."},
            {"id": "o06b", "stratum": "object-nominal", "english": "I replaced only one expired credential.", "ainglish": "I replaced only-one-expired-credential."},
            {"id": "o07b", "stratum": "object-nominal", "english": "the licence allows only internal redistribution.", "ainglish": "the licence allows only-internal-redistribution."},
            {"id": "o08b", "stratum": "object-nominal", "english": "we retained only the independently witnessed receipt.", "ainglish": "we retained only-the-independently-witnessed-receipt."},
            {"id": "a01b", "stratum": "adjunct", "english": "the beacon flashes only on public holidays.", "ainglish": "the beacon flashes only-on-public-holidays."},
            {"id": "a02b", "stratum": "adjunct", "english": "the lock engages only after three warnings.", "ainglish": "the lock engages only-after-three-warnings."},
            {"id": "a03b", "stratum": "adjunct", "english": "the console responds only inside the secure enclave.", "ainglish": "the console responds only-inside-the-secure-enclave."},
            {"id": "a04b", "stratum": "adjunct", "english": "the disclosure proceeds only with counsel present.", "ainglish": "the disclosure proceeds only-with-counsel-present."},
            {"id": "a05b", "stratum": "adjunct", "english": "the reserve activates only during regional outages.", "ainglish": "the reserve activates only-during-regional-outages."},
            {"id": "a06b", "stratum": "adjunct", "english": "the queue advances only for verified requests.", "ainglish": "the queue advances only-for-verified-requests."},
            {"id": "a07b", "stratum": "adjunct", "english": "the drone travels only along surveyed corridors.", "ainglish": "the drone travels only-along-surveyed-corridors."},
            {"id": "a08b", "stratum": "adjunct", "english": "the exception remains valid only before renewal.", "ainglish": "the exception remains valid only-before-renewal."},
        ],
    },
    "only-focus": {
        "slug": "only-focus-the-weld-spans-the-whole-focused-constituent-2",
        "target_hash": "0508f019dae135d82437c2a794276f0d3b5da53d1f4068440e61297d7b570cec",
        "construct": "only-<focus>",
        "tokenizer_version": "0.13.0",
        "models": ["cl100k_base", "o200k_base"],
        "comparison_identity": {
            "comparator_genre": "bare-only-placement-v1",
            "pair_rendering": "inline-single-sentence",
            "tokenizer_roster": ["cl100k_base", "o200k_base"],
        },
        "strata": {"subject": 8, "verb": 8, "object-nominal": 8, "adjunct": 8},
        "items": [
            {"id": "s01", "stratum": "subject", "english": "only Aster compiled the manifest.", "ainglish": "only-Aster compiled the manifest."},
            {"id": "s02", "stratum": "subject", "english": "only Boreal signed the ledger.", "ainglish": "only-Boreal signed the ledger."},
            {"id": "s03", "stratum": "subject", "english": "only the backup custodian accessed the vault.", "ainglish": "only-the-backup-custodian accessed the vault."},
            {"id": "s04", "stratum": "subject", "english": "only three auditors inspected the seal.", "ainglish": "only-three-auditors inspected the seal."},
            {"id": "s05", "stratum": "subject", "english": "only our release manager approved the mirror.", "ainglish": "only-our-release-manager approved the mirror."},
            {"id": "s06", "stratum": "subject", "english": "only the database owner rotated the key.", "ainglish": "only-the-database-owner rotated the key."},
            {"id": "s07", "stratum": "subject", "english": "only agent Seven challenged the result.", "ainglish": "only-agent-Seven challenged the result."},
            {"id": "s08", "stratum": "subject", "english": "only the primary mirror retained the object.", "ainglish": "only-the-primary-mirror retained the object."},
            {"id": "v01", "stratum": "verb", "english": "Nora only inspected the headers.", "ainglish": "Nora only-inspected the headers."},
            {"id": "v02", "stratum": "verb", "english": "the daemon only validated the checksum.", "ainglish": "the daemon only-validated the checksum."},
            {"id": "v03", "stratum": "verb", "english": "we only copied the metadata.", "ainglish": "we only-copied the metadata."},
            {"id": "v04", "stratum": "verb", "english": "they only reordered the queue.", "ainglish": "they only-reordered the queue."},
            {"id": "v05", "stratum": "verb", "english": "the reviewer only annotated the failure.", "ainglish": "the reviewer only-annotated the failure."},
            {"id": "v06", "stratum": "verb", "english": "I only compressed the bundle.", "ainglish": "I only-compressed the bundle."},
            {"id": "v07", "stratum": "verb", "english": "Kepler only opened the attachment.", "ainglish": "Kepler only-opened the attachment."},
            {"id": "v08", "stratum": "verb", "english": "the worker only counted the records.", "ainglish": "the worker only-counted the records."},
            {"id": "o01", "stratum": "object-nominal", "english": "the runner modified only the timeout.", "ainglish": "the runner modified only-the-timeout."},
            {"id": "o02", "stratum": "object-nominal", "english": "we mirrored only two public bundles.", "ainglish": "we mirrored only-two-public-bundles."},
            {"id": "o03", "stratum": "object-nominal", "english": "the filter retained only urgent alerts.", "ainglish": "the filter retained only-urgent-alerts."},
            {"id": "o04", "stratum": "object-nominal", "english": "Mira disclosed only her final estimate.", "ainglish": "Mira disclosed only-her-final-estimate."},
            {"id": "o05", "stratum": "object-nominal", "english": "the scanner indexed only the signed archive.", "ainglish": "the scanner indexed only-the-signed-archive."},
            {"id": "o06", "stratum": "object-nominal", "english": "I restored only one damaged shard.", "ainglish": "I restored only-one-damaged-shard."},
            {"id": "o07", "stratum": "object-nominal", "english": "the policy permits only read operations.", "ainglish": "the policy permits only-read-operations."},
            {"id": "o08", "stratum": "object-nominal", "english": "we published only the compact report.", "ainglish": "we published only-the-compact-report."},
            {"id": "a01", "stratum": "adjunct", "english": "the scheduler wakes only on weekdays.", "ainglish": "the scheduler wakes only-on-weekdays."},
            {"id": "a02", "stratum": "adjunct", "english": "the alert fires only after two failures.", "ainglish": "the alert fires only-after-two-failures."},
            {"id": "a03", "stratum": "adjunct", "english": "the service listens only inside the private network.", "ainglish": "the service listens only-inside-the-private-network."},
            {"id": "a04", "stratum": "adjunct", "english": "the refund runs only with manager consent.", "ainglish": "the refund runs only-with-manager-consent."},
            {"id": "a05", "stratum": "adjunct", "english": "the archive unlocks only during the audit window.", "ainglish": "the archive unlocks only-during-the-audit-window."},
            {"id": "a06", "stratum": "adjunct", "english": "the webhook retries only for transient errors.", "ainglish": "the webhook retries only-for-transient-errors."},
            {"id": "a07", "stratum": "adjunct", "english": "the robot moves only along marked lanes.", "ainglish": "the robot moves only-along-marked-lanes."},
            {"id": "a08", "stratum": "adjunct", "english": "the rule applies only before finalization.", "ainglish": "the rule applies only-before-finalization."},
        ],
    },
    "verifier-at": {
        "slug": "verifier-at-vantage-tier-route-verification-effort-and-price",
        "target_hash": "9b7692e1e03da59878b221f3346513d50a97fef8dd6a010745dd7518d56b05e9",
        "construct": "verifier-at(<vantage>;<tier>)",
        "tokenizer_version": "0.13.0",
        "models": ["cl100k_base", "o200k_base"],
        "comparison_identity": {
            "comparator_genre": "lossless-mapping-in-context-v1",
            "pair_rendering": "inline-single-sentence",
            "tokenizer_roster": ["cl100k_base", "o200k_base"],
        },
        "strata": {"re-derivable": 6, "witnessed": 5, "testimony": 5},
        "items": [
            {"id": "r01", "stratum": "re-derivable", "english": "The image has digest d91f, and its correctness is checkable from the public registry by recomputing from public inputs and trusting nobody.", "ainglish": "The image has digest d91f verifier-at(public-registry;re-derivable)."},
            {"id": "r02", "stratum": "re-derivable", "english": "The dependency lock resolves to version 8.4, and its correctness is checkable from the public lockfile by recomputing from public inputs and trusting nobody.", "ainglish": "The dependency lock resolves to version 8.4 verifier-at(public-lockfile;re-derivable)."},
            {"id": "r03", "stratum": "re-derivable", "english": "The dataset contains 4096 rows, and its correctness is checkable from the published shard by recomputing from public inputs and trusting nobody.", "ainglish": "The dataset contains 4096 rows verifier-at(published-shard;re-derivable)."},
            {"id": "r04", "stratum": "re-derivable", "english": "The package archive matches checksum 7c2a, and its correctness is checkable from the release assets by recomputing from public inputs and trusting nobody.", "ainglish": "The package archive matches checksum 7c2a verifier-at(release-assets;re-derivable)."},
            {"id": "r05", "stratum": "re-derivable", "english": "The certificate expires on 14 October, and its correctness is checkable from the public certificate by recomputing from public inputs and trusting nobody.", "ainglish": "The certificate expires on 14 October verifier-at(public-certificate;re-derivable)."},
            {"id": "r06", "stratum": "re-derivable", "english": "The source archive contains commit 2f8b, and its correctness is checkable from the public repository by recomputing from public inputs and trusting nobody.", "ainglish": "The source archive contains commit 2f8b verifier-at(public-repository;re-derivable)."},
            {"id": "w01", "stratum": "witnessed", "english": "The secure door opened at 07:12, and its correctness is checkable from the access-controller event left by an independent party with a stake.", "ainglish": "The secure door opened at 07:12 verifier-at(access-controller-event;witnessed)."},
            {"id": "w02", "stratum": "witnessed", "english": "The transfer settled yesterday, and its correctness is checkable from the receiving bank's receipt left by an independent party with a stake.", "ainglish": "The transfer settled yesterday verifier-at(receiving-bank-receipt;witnessed)."},
            {"id": "w03", "stratum": "witnessed", "english": "The sample arrived frozen, and its correctness is checkable from the laboratory intake record left by an independent party with a stake.", "ainglish": "The sample arrived frozen verifier-at(laboratory-intake;witnessed)."},
            {"id": "w04", "stratum": "witnessed", "english": "The device was calibrated in June, and its correctness is checkable from the service certificate left by an independent party with a stake.", "ainglish": "The device was calibrated in June verifier-at(service-certificate;witnessed)."},
            {"id": "w05", "stratum": "witnessed", "english": "The pager was acknowledged at 03:15, and its correctness is checkable from the paging provider's event left by an independent party with a stake.", "ainglish": "The pager was acknowledged at 03:15 verifier-at(paging-provider-event;witnessed)."},
            {"id": "t01", "stratum": "testimony", "english": "The interface seemed clearer, and its correctness rests on the claimant's own word with no independent trace.", "ainglish": "The interface seemed clearer verifier-at(self;testimony)."},
            {"id": "t02", "stratum": "testimony", "english": "The draft felt complete, and its correctness rests on the claimant's own word with no independent trace.", "ainglish": "The draft felt complete verifier-at(self;testimony)."},
            {"id": "t03", "stratum": "testimony", "english": "The negotiation sounded constructive, and its correctness rests on the claimant's own word with no independent trace.", "ainglish": "The negotiation sounded constructive verifier-at(self;testimony)."},
            {"id": "t04", "stratum": "testimony", "english": "The experiment looked promising, and its correctness rests on the claimant's own word with no independent trace.", "ainglish": "The experiment looked promising verifier-at(self;testimony)."},
            {"id": "t05", "stratum": "testimony", "english": "The plan appears practical, and its correctness rests on the claimant's own word with no independent trace.", "ainglish": "The plan appears practical verifier-at(self;testimony)."},
        ],
    },
    "typed-missing-values": {
        "slug": "value-unknown-value-none-value-redacted-redactor-ref-value",
        "target_hash": "6a9d6e20bd982e7f647e018a92fc842570e30c3d15578d625eed1f6bee9948eb",
        "construct": "value-unknown / value-none / value-redacted / value-inapplicable",
        "tokenizer_version": "0.14.0",
        "models": ["cl100k_base", "o200k_base", "p50k_base"],
        "comparison_identity": {
            "comparator_genre": "concise-ordinary-english-missing-value-v1",
            "pair_rendering": "single-property-statement",
            "tokenizer_roster": ["cl100k_base", "o200k_base", "p50k_base"],
        },
        "strata": {
            "value-unknown": 4,
            "value-none": 4,
            "value-redacted": 4,
            "value-inapplicable": 4,
        },
        "items": [
            {"id": "u01", "stratum": "value-unknown", "english": "The support tier has not been established.", "ainglish": "support-tier: value-unknown."},
            {"id": "u02", "stratum": "value-unknown", "english": "The current custodian is unknown.", "ainglish": "current-custodian: value-unknown."},
            {"id": "u03", "stratum": "value-unknown", "english": "The device location has not been determined.", "ainglish": "device-location: value-unknown."},
            {"id": "u04", "stratum": "value-unknown", "english": "Whether a recovery key exists is unknown.", "ainglish": "recovery-key: value-unknown."},
            {"id": "n01", "stratum": "value-none", "english": "The account has no recovery email.", "ainglish": "recovery-email: value-none."},
            {"id": "n02", "stratum": "value-none", "english": "The schema asserts that no alias exists.", "ainglish": "alias: value-none."},
            {"id": "n03", "stratum": "value-none", "english": "This record has no secondary owner.", "ainglish": "secondary-owner: value-none."},
            {"id": "n04", "stratum": "value-none", "english": "No termination date exists for this agreement.", "ainglish": "termination-date: value-none."},
            {"id": "r01", "stratum": "value-redacted", "english": "The auditor intentionally removed the existing witness name from this copy.", "ainglish": "witness-name: value-redacted(auditor)."},
            {"id": "r02", "stratum": "value-redacted", "english": "The publisher deliberately omitted the existing address from this edition.", "ainglish": "address: value-redacted(publisher)."},
            {"id": "r03", "stratum": "value-redacted", "english": "Compliance intentionally removed the existing account number from this report.", "ainglish": "account-number: value-redacted(compliance)."},
            {"id": "r04", "stratum": "value-redacted", "english": "The curator deliberately withheld the existing donor identity from this catalogue.", "ainglish": "donor-identity: value-redacted(curator)."},
            {"id": "i01", "stratum": "value-inapplicable", "english": "Bicycles have no engine serial under this schema.", "ainglish": "engine-serial: value-inapplicable."},
            {"id": "i02", "stratum": "value-inapplicable", "english": "A perpetual licence has no expiry field under this schema.", "ainglish": "licence-expiry: value-inapplicable."},
            {"id": "i03", "stratum": "value-inapplicable", "english": "A text file has no frame rate under this schema.", "ainglish": "frame-rate: value-inapplicable."},
            {"id": "i04", "stratum": "value-inapplicable", "english": "A virtual service has no physical shelf location under this schema.", "ainglish": "shelf-location: value-inapplicable."},
        ],
    },
    "grader-eq-graded": {
        "slug": "grader-eq-graded",
        "target_hash": "013f8325e89778e98519f0e19bb1d64cd073e4e1fed0efcc6652545630475d7c",
        "construct": "grader=graded",
        "tokenizer_version": "0.13.0",
        "models": ["cl100k_base", "o200k_base"],
        "comparison_identity": {
            "comparator_genre": "lossless-mapping-in-context-v1",
            "pair_rendering": "inline-single-sentence",
            "tokenizer_roster": ["cl100k_base", "o200k_base"],
        },
        "strata": {"self-reference": 16},
        "items": [
            {"id": "g01", "stratum": "self-reference", "english": "The parser validator imports the parser's own grammar, so its pass certifies agreement-with-self rather than correctness.", "ainglish": "The parser validator is grader=graded."},
            {"id": "g02", "stratum": "self-reference", "english": "The fraud review is performed by the analyst whose labels are being reviewed, so its pass certifies agreement-with-self rather than correctness.", "ainglish": "The fraud review is grader=graded."},
            {"id": "g03", "stratum": "self-reference", "english": "The agent assigns the score to its own answer, so the score certifies agreement-with-self rather than correctness.", "ainglish": "The answer score is grader=graded."},
            {"id": "g04", "stratum": "self-reference", "english": "The recommender is evaluated using relevance labels produced by the same recommender, so the result certifies agreement-with-self rather than correctness.", "ainglish": "The recommender evaluation is grader=graded."},
            {"id": "g05", "stratum": "self-reference", "english": "The forecaster also writes the outcome labels used to score the forecast, so the score certifies agreement-with-self rather than correctness.", "ainglish": "The forecast score is grader=graded."},
            {"id": "g06", "stratum": "self-reference", "english": "The OCR check compares the transcription with a second transcription from the same engine, so agreement certifies agreement-with-self rather than correctness.", "ainglish": "The OCR check is grader=graded."},
            {"id": "g07", "stratum": "self-reference", "english": "The serializer test derives its expected bytes by calling the serializer under test, so the pass certifies agreement-with-self rather than correctness.", "ainglish": "The serializer test is grader=graded."},
            {"id": "g08", "stratum": "self-reference", "english": "The policy audit reads both the policy and its expected findings from one generated file, so the pass certifies agreement-with-self rather than correctness.", "ainglish": "The policy audit is grader=graded."},
            {"id": "g09", "stratum": "self-reference", "english": "The route checker builds its expected URLs from the router it checks, so the pass certifies agreement-with-self rather than correctness.", "ainglish": "The route checker is grader=graded."},
            {"id": "g10", "stratum": "self-reference", "english": "The classifier judges its predictions using labels it generated itself, so the score certifies agreement-with-self rather than correctness.", "ainglish": "The classifier score is grader=graded."},
            {"id": "g11", "stratum": "self-reference", "english": "The inventory audit compares the warehouse list with a copy from the same warehouse system, so the match certifies agreement-with-self rather than correctness.", "ainglish": "The inventory audit is grader=graded."},
            {"id": "g12", "stratum": "self-reference", "english": "The spreadsheet verifies its totals using the same broken formula copied into a check column, so the match certifies agreement-with-self rather than correctness.", "ainglish": "The spreadsheet check is grader=graded."},
            {"id": "g13", "stratum": "self-reference", "english": "The benchmark answer key was generated by the system taking the benchmark, so the pass certifies agreement-with-self rather than correctness.", "ainglish": "The benchmark is grader=graded."},
            {"id": "g14", "stratum": "self-reference", "english": "The database migration verifies rows with a query copied from the migration itself, so the pass certifies agreement-with-self rather than correctness.", "ainglish": "The migration verification is grader=graded."},
            {"id": "g15", "stratum": "self-reference", "english": "The sensor calibrates itself against its own current reading, so the green status certifies agreement-with-self rather than correctness.", "ainglish": "The sensor calibration is grader=graded."},
            {"id": "g16", "stratum": "self-reference", "english": "The summary is rated for fidelity by the model that wrote it, so the rating certifies agreement-with-self rather than correctness.", "ainglish": "The summary rating is grader=graded."},
        ],
    },
}
