"""Frozen fresh-input carriers for three live token-settlement targets."""

CAMPAIGNS = {
    "part-boundary": {
        "slug": "part-chosen-rule-part-capped-limiter-was-the-edge-of-the-set",
        "target": "7389992437ef0dc433f29351fbf30fa73371bfcd6aabde40025761cb19639133",
        "construct": "part-chosen / part-capped",
        "comparison_identity": {
            "comparator_genre": "complete-careful-english-boundary-source-v1",
            "pair_rendering": "standalone-coverage-report",
            "tokenizer_roster": ["cl100k_base", "o200k_base"],
        },
        "items": [
            {"id": "chosen-01", "stratum": "part-chosen", "ainglish": "part-chosen(severity-quartile): the 48 alerts.", "english": "I examined the 48 alerts that the severity-quartile rule chose, out of the 193 recorded; the rule picked which alerts to examine."},
            {"id": "chosen-02", "stratum": "part-chosen", "ainglish": "part-chosen(alphabetic-slice): the 72 suppliers.", "english": "I reviewed the 72 suppliers that the alphabetic-slice rule chose, out of the 418 listed; the rule picked which suppliers to review."},
            {"id": "chosen-03", "stratum": "part-chosen", "ainglish": "part-chosen(random-seed-77): the 96 sessions.", "english": "I inspected the 96 sessions that random seed 77 chose, out of the 630 captured; that rule picked which sessions to inspect."},
            {"id": "chosen-04", "stratum": "part-chosen", "ainglish": "part-chosen(region-rule): the 35 clinics.", "english": "I checked the 35 clinics that the region rule chose, out of the 204 registered; the rule picked which clinics to check."},
            {"id": "chosen-05", "stratum": "part-chosen", "ainglish": "part-chosen(age-window): the 60 certificates.", "english": "I audited the 60 certificates that the age-window rule chose, out of the 355 issued; the rule picked which certificates to audit."},
            {"id": "chosen-06", "stratum": "part-chosen", "ainglish": "part-chosen(weekday-rule): the 44 deliveries.", "english": "I traced the 44 deliveries that the weekday rule chose, out of the 287 logged; the rule picked which deliveries to trace."},
            {"id": "chosen-07", "stratum": "part-chosen", "ainglish": "part-chosen(confidence-threshold): the 81 classifications.", "english": "I reviewed the 81 classifications that the confidence-threshold rule chose, out of the 502 produced; the rule picked which classifications to review."},
            {"id": "chosen-08", "stratum": "part-chosen", "ainglish": "part-chosen(language-rule): the 28 transcripts.", "english": "I read the 28 transcripts that the language rule chose, out of the 176 available; the rule picked which transcripts to read."},
            {"id": "capped-01", "stratum": "part-capped", "ainglish": "part-capped(api-page-120): the 120 alerts.", "english": "I examined 120 of the 463 alerts; the API stopped at 120, so I could not examine the remaining 343 alerts."},
            {"id": "capped-02", "stratum": "part-capped", "ainglish": "part-capped(export-row-500): the 500 suppliers.", "english": "I reviewed 500 of the 842 suppliers; the export stopped at 500 rows, so I could not review the remaining 342 suppliers."},
            {"id": "capped-03", "stratum": "part-capped", "ainglish": "part-capped(timeout-90s): the 67 sessions.", "english": "I inspected 67 of the 390 sessions; the scan timed out after 90 seconds, so I could not inspect the remaining sessions."},
            {"id": "capped-04", "stratum": "part-capped", "ainglish": "part-capped(quota-40): the 40 clinics.", "english": "I checked 40 of the 129 clinics; the quota stopped me at 40, so I could not check the remaining 89 clinics."},
            {"id": "capped-05", "stratum": "part-capped", "ainglish": "part-capped(permission-west): the 53 certificates.", "english": "I audited 53 of the 311 certificates; my permission covered only the western division, so I could not audit the remainder."},
            {"id": "capped-06", "stratum": "part-capped", "ainglish": "part-capped(memory-8gb): the 74 deliveries.", "english": "I traced 74 of the 268 deliveries; the eight-gigabyte memory limit stopped the trace, so I could not examine the remainder."},
            {"id": "capped-07", "stratum": "part-capped", "ainglish": "part-capped(archive-window-30d): the 91 classifications.", "english": "I reviewed 91 of the 477 classifications; the archive exposed only thirty days, so I could not review the older classifications."},
            {"id": "capped-08", "stratum": "part-capped", "ainglish": "part-capped(console-limit-1000): the 1,000 transcripts.", "english": "I read 1,000 of the 1,684 transcripts; the console stopped at 1,000, so I could not read the remaining 684 transcripts."},
        ],
    },
    "grader-graded": {
        "slug": "grader-eq-graded",
        "target": "013f8325e89778e98519f0e19bb1d64cd073e4e1fed0efcc6652545630475d7c",
        "construct": "grader=graded",
        "comparison_identity": {
            "comparator_genre": "lossless-mapping-in-context-v1",
            "pair_rendering": "inline-single-sentence",
            "tokenizer_roster": ["cl100k_base", "o200k_base"],
        },
        "items": [
            {"id": "grader-01", "ainglish": "The permissions audit is grader=graded.", "english": "The permissions audit derives its expected roles from the same permission table it evaluates, so a pass only certifies agreement-with-self, not correctness."},
            {"id": "grader-02", "ainglish": "That green parser check is grader=graded.", "english": "That green parser check generates its expected tree with the parser under test, so a pass only certifies agreement-with-self, not correctness."},
            {"id": "grader-03", "ainglish": "The forecast review is grader=graded.", "english": "The forecast review asks the forecasting system to judge its own forecasts, so approval only certifies agreement-with-self, not correctness."},
            {"id": "grader-04", "ainglish": "Our deduplication test is grader=graded.", "english": "Our deduplication test builds the expected identifiers with the same normalizer as the code under test, so a match only certifies agreement-with-self, not correctness."},
            {"id": "grader-05", "ainglish": "The route conformance check is grader=graded.", "english": "The route conformance check reads its expected routes from the router it checks, so a green result only certifies agreement-with-self, not correctness."},
            {"id": "grader-06", "ainglish": "This redaction review is grader=graded.", "english": "This redaction review lets the redaction engine decide whether its own output is safe, so approval only certifies agreement-with-self, not correctness."},
            {"id": "grader-07", "ainglish": "The inventory reconciliation is grader=graded.", "english": "The inventory reconciliation copies both totals from the same warehouse feed, so equality only certifies agreement-with-self, not correctness."},
            {"id": "grader-08", "ainglish": "That citation evaluator is grader=graded.", "english": "That citation evaluator uses the answer generator's own source selection as its reference, so a pass only certifies agreement-with-self, not correctness."},
            {"id": "grader-09", "ainglish": "The encoding round-trip is grader=graded.", "english": "The encoding round-trip uses the same faulty table to encode and decode, so recovery only certifies agreement-with-self, not correctness."},
            {"id": "grader-10", "ainglish": "Our policy compliance score is grader=graded.", "english": "Our policy compliance score is assigned by the system whose behavior the policy constrains, so a pass only certifies agreement-with-self, not correctness."},
            {"id": "grader-11", "ainglish": "The extraction benchmark is grader=graded.", "english": "The extraction benchmark treats labels produced by the extractor as ground truth for that extractor, so agreement only certifies agreement-with-self, not correctness."},
            {"id": "grader-12", "ainglish": "This cache validation is grader=graded.", "english": "This cache validation compares stored values with expectations computed from the same cached values, so a pass only certifies agreement-with-self, not correctness."},
            {"id": "grader-13", "ainglish": "The moderation appeal is grader=graded.", "english": "The moderation appeal is decided solely by the classifier whose decision is under appeal, so confirmation only certifies agreement-with-self, not correctness."},
            {"id": "grader-14", "ainglish": "That unit conversion test is grader=graded.", "english": "That unit conversion test derives expected quantities through the same conversion function it tests, so a match only certifies agreement-with-self, not correctness."},
            {"id": "grader-15", "ainglish": "The dependency audit is grader=graded.", "english": "The dependency audit trusts the resolver's own lock graph as the independent oracle for that resolver, so a pass only certifies agreement-with-self, not correctness."},
            {"id": "grader-16", "ainglish": "Our transcript accuracy review is grader=graded.", "english": "Our transcript accuracy review asks the transcription model to verify its own words without an external recording check, so approval only certifies agreement-with-self, not correctness."},
        ],
    },
    "sharing-topology": {
        "slug": "send-snapshot-version-ref-to-recipient-grant-live-view",
        "target": "3ac9910f538f68f962193586b253cc212a0c1ca7b76ff2f9705189549906ad4d",
        "construct": "send-snapshot / grant-live-view",
        "comparison_identity": {
            "comparator_genre": "complete-careful-english-topology-v1",
            "pair_rendering": "typed-action-in-context",
            "tokenizer_roster": ["cl100k_base", "o200k_base"],
        },
        "items": [
            {"id": "snapshot-01", "stratum": "send-snapshot", "ainglish": "Please send-snapshot(briefing@v12, to=Mira).", "english": "Send Mira an independent fixed copy of briefing version 12; later source edits or access revocation will not alter or withdraw that copy."},
            {"id": "snapshot-02", "stratum": "send-snapshot", "ainglish": "Orin will send-snapshot(ledger@2026-09-03, to=finance).", "english": "Send finance an independent fixed copy of the ledger as of 2026-09-03; later edits to the live ledger will not alter or withdraw that copy."},
            {"id": "snapshot-03", "stratum": "send-snapshot", "ainglish": "send-snapshot(dataset@sha256-c81a, to=review).", "english": "Send review an independent fixed copy of the dataset at revision sha256-c81a; later dataset changes will not alter or withdraw that copy."},
            {"id": "snapshot-04", "stratum": "send-snapshot", "ainglish": "Did Pavo send-snapshot(spec@r17, to=vendors)?", "english": "Did Pavo send the vendors an independent fixed copy of specification revision r17, which later source changes cannot alter or withdraw?"},
            {"id": "snapshot-05", "stratum": "send-snapshot", "ainglish": "Do not send-snapshot(schedule@final, to=dispatch).", "english": "Do not send dispatch an independent fixed copy of the final schedule; dispatch must continue reading the changing canonical schedule."},
            {"id": "snapshot-06", "stratum": "send-snapshot", "ainglish": "Please send-snapshot(footage@original, to=insurer).", "english": "Send the insurer an independent fixed copy of the original footage; later source deletion or editing will not alter or withdraw that copy."},
            {"id": "snapshot-07", "stratum": "send-snapshot", "ainglish": "send-snapshot(manual@2026-08-31, to=field-team).", "english": "Send the field team an independent fixed copy of the manual as of 2026-08-31; later revisions will not alter or withdraw that copy."},
            {"id": "snapshot-08", "stratum": "send-snapshot", "ainglish": "Kite requested send-snapshot(model@release-6, to=safety).", "english": "Kite requested an independent fixed copy of model release 6 for safety; later retraining or access revocation will not alter or withdraw that copy."},
            {"id": "live-01", "stratum": "grant-live-view", "ainglish": "Please grant-live-view(briefing, to=Mira).", "english": "Grant Mira revocable read-only access to the canonical briefing, showing its current contents on each successful read; do not send an independent fixed copy."},
            {"id": "live-02", "stratum": "grant-live-view", "ainglish": "Orin will grant-live-view(ledger, to=finance).", "english": "Grant finance revocable read-only access to the canonical ledger, showing its current contents on each successful read; do not send an independent fixed copy."},
            {"id": "live-03", "stratum": "grant-live-view", "ainglish": "Did Pavo grant-live-view(dataset, to=review)?", "english": "Did Pavo grant review revocable read-only access to the canonical dataset, showing its current contents on each successful read without sending a fixed copy?"},
            {"id": "live-04", "stratum": "grant-live-view", "ainglish": "grant-live-view(spec, to=vendors).", "english": "Grant the vendors revocable read-only access to the canonical specification, showing its current contents on each successful read; do not send an independent fixed copy."},
            {"id": "live-05", "stratum": "grant-live-view", "ainglish": "Do not grant-live-view(schedule, to=dispatch).", "english": "Do not grant dispatch revocable read-only access to the canonical schedule, and do not expose that live object to dispatch."},
            {"id": "live-06", "stratum": "grant-live-view", "ainglish": "Please grant-live-view(footage, to=insurer).", "english": "Grant the insurer revocable read-only access to the canonical footage, showing its current contents on each successful read; do not send an independent fixed copy."},
            {"id": "live-07", "stratum": "grant-live-view", "ainglish": "grant-live-view(manual, to=field-team).", "english": "Grant the field team revocable read-only access to the canonical manual, showing its current contents on each successful read; do not send an independent fixed copy."},
            {"id": "live-08", "stratum": "grant-live-view", "ainglish": "Kite requested grant-live-view(model, to=safety).", "english": "Kite requested revocable read-only access for safety to the canonical model, showing current contents on each successful read without sending a fixed copy."},
        ],
    },
}
